### ISSUE TITLE
Linkedin sign in using wrong PW

### ISSUE THREAD

**Issue by Mythri295** [SkillPad/Fixit#20] opened 2018-12-06 10:24 UTC
Signed in using Linkedin - gave a wrong pw.

Error message is not in sync with the GUI.

![screen shot 2018-12-06 at 3 50 58 pm](https://user-images.githubusercontent.com/30720308/49578167-1c858a80-f96f-11e8-8745-38ab25fb228c.png)

**Comment by amit-choudhary** [comment] 2019-01-13 23:04
Duplicate of https://github.com/SkillPad/Fixit/issues/13

**Closed as completed** 2019-03-14 09:58 UTC
Labels: duplicate
